In [63]:
import pandas as pd
import numpy as np

In [80]:
#Loading all data frames into our python notebook

data78 = pd.read_csv('data78.csv', low_memory=False)
data89 = pd.read_csv('data89.csv', low_memory=False)
data910 = pd.read_csv('data910.csv', low_memory=False)
data1011 = pd.read_csv('data1011.csv', low_memory=False)
data1112 = pd.read_csv('data1112.csv', low_memory=False)
data1213 = pd.read_csv('data1213.csv', low_memory=False)
data1314 = pd.read_csv('data1314.csv', low_memory=False)
data1415 = pd.read_csv('data1415.csv', low_memory=False)
data1516 = pd.read_csv('data1516.csv', low_memory=False)
data1617 = pd.read_csv('data1617.csv', low_memory=False)

In [76]:
#loading column dictionary

cnames=pd.read_csv('c_name.csv')

In [77]:
#taking our column names from the dictionary and converting it to a list

c_list=cnames['column name'].values.tolist()

In [78]:
#Extracting all the column names that we require

data1=data78[[c for c in data78.columns if c in c_list]]
data2=data89[[c for c in data89.columns if c in c_list]]
data3=data910[[c for c in data910.columns if c in c_list]]
data4=data1011[[c for c in data1011.columns if c in c_list]]
data5=data1112[[c for c in data1112.columns if c in c_list]]
data6=data1213[[c for c in data1213.columns if c in c_list]]
data7=data1314[[c for c in data1314.columns if c in c_list]]
data8=data1415[[c for c in data1415.columns if c in c_list]]
data9=data1516[[c for c in data1516.columns if c in c_list]]
data10=data1617[[c for c in data1617.columns if c in c_list]]

In [79]:
#Exporting our new dataframes

data1.to_csv('data1.csv')
data2.to_csv('data2.csv')
data3.to_csv('data3.csv')
data4.to_csv('data4.csv')
data5.to_csv('data5.csv')
data6.to_csv('data6.csv')
data7.to_csv('data7.csv')
data8.to_csv('data8.csv')
data9.to_csv('data9.csv')
data10.to_csv('data10.csv')

In [115]:
# Finding null values in dataframe and storing the column names with null values in a list

df1_na= data1.isna()
count_true=0
count_false=0
list_null_col1= []
for c in c_list:
#     print(c)
    col= list(df1_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col1.append(c)

# print(list_null_col)

In [116]:
# Finding null values in dataframe and storing the column names with null values in a list

df2_na= data2.isna()
count_true=0
count_false=0
list_null_col2= []
for c in c_list:
#     print(c)
    col= list(df2_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col2.append(c)

# print(list_null_col)

In [117]:
# Finding null values in dataframe and storing the column names with null values in a list

df3_na= data3.isna()
count_true=0
count_false=0
list_null_col3= []
for c in c_list:
#     print(c)
    col= list(df3_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col3.append(c)

# print(list_null_col)

In [118]:
# Finding null values in dataframe and storing the column names with null values in a list

df4_na= data4.isna()
count_true=0
count_false=0
list_null_col4= []
for c in c_list:
#     print(c)
    col= list(df4_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col4.append(c)

# print(list_null_col)

In [119]:
# Finding null values in dataframe and storing the column names with null values in a list

df5_na= data5.isna()
count_true=0
count_false=0
list_null_col5= []
for c in c_list:
#     print(c)
    col= list(df5_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col5.append(c)

# print(list_null_col)

In [120]:
# Finding null values in dataframe and storing the column names with null values in a list

df6_na= data6.isna()
count_true=0
count_false=0
list_null_col6= []
for c in c_list:
#     print(c)
    col= list(df6_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col6.append(c)

# print(list_null_col)

In [121]:
# Finding null values in dataframe and storing the column names with null values in a list

df7_na= data7.isna()
count_true=0
count_false=0
list_null_col7= []
for c in c_list:
#     print(c)
    col= list(df7_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col7.append(c)

# print(list_null_col)

In [122]:
# Finding null values in dataframe and storing the column names with null values in a list

df8_na= data8.isna()
count_true=0
count_false=0
list_null_col8= []
for c in c_list:
#     print(c)
    col= list(df8_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col8.append(c)

# print(list_null_col)

In [123]:
# Finding null values in dataframe and storing the column names with null values in a list

df9_na= data9.isna()
count_true=0
count_false=0
list_null_col9= []
for c in c_list:
#     print(c)
    col= list(df9_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col9.append(c)

# print(list_null_col)

In [125]:
# Finding null values in dataframe and storing the column names with null values in a list

df10_na= data10.isna()
count_true=0
count_false=0
list_null_col10= []
for c in c_list:
#     print(c)
    col= list(df10_na[c])
    for r in col:
        if r == True:
            count_true+=1
#             print(count_true)
        else:
            count_false+=1
    if count_true >= count_false:
        list_null_col10.append(c)

# print(list_null_col)

In [155]:
# Making a list of all the null value lists

list_null=[list_null_col1,list_null_col2,list_null_col3,list_null_col4,list_null_col5,list_null_col6,list_null_col7,list_null_col8,list_null_col9,list_null_col10]

In [156]:
#Converting list into a numpy array to find unique values, then converting it back to a list

x=np.array(list_null)
y=np.unique(x)
z=list(y)

In [166]:
print(z)

[['ACTEN75', 'ACTMT25', 'ACTMT75', 'ACTWR25', 'ACTWR75', 'ACTCMMID', 'ACTENMID', 'ACTMTMID', 'ACTWRMID', 'SAT_AVG', 'SAT_AVG_ALL', 'PCIP01', 'PCIP03', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP10', 'PCIP11', 'PCIP12', 'PCIP13', 'OVERALL_YR8_N', 'LO_INC_YR8_N', 'MD_INC_YR8_N', 'HI_INC_YR8_N', 'DEP_YR8_N', 'IND_YR8_N', 'FEMALE_YR8_N', 'MALE_YR8_N', 'PELL_YR8_N', 'NOPELL_YR8_N', 'LOAN_YR8_N', 'NOLOAN_YR8_N', 'FIRSTGEN_YR8_N', 'NOT1STGEN_YR8_N', 'DEBT_MDN', 'GRAD_DEBT_MDN', 'WDRAW_DEBT_MDN', 'LO_INC_DEBT_MDN', 'MD_INC_DEBT_MDN', 'HI_INC_DEBT_MDN', 'DEP_DEBT_MDN', 'IND_DEBT_MDN', 'PELL_DEBT_MDN', 'NOPELL_DEBT_MDN', 'FEMALE_DEBT_MDN', 'MALE_DEBT_MDN', 'FIRSTGEN_DEBT_MDN'], ['ACTWR25', 'ACTWR75', 'ACTCMMID', 'ACTENMID', 'ACTMTMID', 'ACTWRMID', 'SAT_AVG', 'SAT_AVG_ALL', 'PCIP01', 'PCIP03', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP10'], ['ACTWR25', 'ACTWR75', 'ACTCMMID', 'ACTENMID', 'ACTMTMID', 'ACTWRMID', 'SAT_AVG', 'SAT_AVG_ALL', 'PCIP01', 'PCIP03', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP10', 'PCIP11'], ['ACTWR75', 'ACTCMMID', 'ACTENMID', 'ACTMTMID', 'ACTWRMID', 'SAT_AVG', 'SAT_AVG_ALL', 'PCIP01', 'PCIP03', 'PCIP04', 'PCIP05', 'PCIP09']]

In [174]:
z

[['ACTEN75',
  'ACTMT25',
  'ACTMT75',
  'ACTWR25',
  'ACTWR75',
  'ACTCMMID',
  'ACTENMID',
  'ACTMTMID',
  'ACTWRMID',
  'SAT_AVG',
  'SAT_AVG_ALL',
  'PCIP01',
  'PCIP03',
  'PCIP04',
  'PCIP05',
  'PCIP09',
  'PCIP10',
  'PCIP11',
  'PCIP12',
  'PCIP13',
  'OVERALL_YR8_N',
  'LO_INC_YR8_N',
  'MD_INC_YR8_N',
  'HI_INC_YR8_N',
  'DEP_YR8_N',
  'IND_YR8_N',
  'FEMALE_YR8_N',
  'MALE_YR8_N',
  'PELL_YR8_N',
  'NOPELL_YR8_N',
  'LOAN_YR8_N',
  'NOLOAN_YR8_N',
  'FIRSTGEN_YR8_N',
  'NOT1STGEN_YR8_N',
  'DEBT_MDN',
  'GRAD_DEBT_MDN',
  'WDRAW_DEBT_MDN',
  'LO_INC_DEBT_MDN',
  'MD_INC_DEBT_MDN',
  'HI_INC_DEBT_MDN',
  'DEP_DEBT_MDN',
  'IND_DEBT_MDN',
  'PELL_DEBT_MDN',
  'NOPELL_DEBT_MDN',
  'FEMALE_DEBT_MDN',
  'MALE_DEBT_MDN',
  'FIRSTGEN_DEBT_MDN'],
 ['ACTWR25',
  'ACTWR75',
  'ACTCMMID',
  'ACTENMID',
  'ACTMTMID',
  'ACTWRMID',
  'SAT_AVG',
  'SAT_AVG_ALL',
  'PCIP01',
  'PCIP03',
  'PCIP04',
  'PCIP05',
  'PCIP09',
  'PCIP10'],
 ['ACTWR25',
  'ACTWR75',
  'ACTCMMID',
  'ACTENMID',
  'ACTMTMID',
  'ACTWRMID',
  'SAT_AVG',
  'SAT_AVG_ALL',
  'PCIP01',
  'PCIP03',
  'PCIP04',
  'PCIP05',
  'PCIP09',
  'PCIP10',
  'PCIP11'],
 ['ACTWR75',
  'ACTCMMID',
  'ACTENMID',
  'ACTMTMID',
  'ACTWRMID',
  'SAT_AVG',
  'SAT_AVG_ALL',
  'PCIP01',
  'PCIP03',
  'PCIP04',
  'PCIP05',
  'PCIP09']]

In [209]:
null_count={}
count=0
flag=0

        
def checker(n):
    for x in range(0,10):
        if n not in list_null[x]:
#             flag=flag+1
            print(n)
        null_count.update({n:flag})

for a in range(0,4):
    for v in z[a]:
        checker(v)
null_count

ACTEN75
ACTEN75
ACTEN75
ACTEN75
ACTEN75
ACTEN75
ACTEN75
ACTEN75
ACTEN75
ACTMT25
ACTMT25
ACTMT25
ACTMT25
ACTMT25
ACTMT25
ACTMT25
ACTMT25
ACTMT25
ACTMT75
ACTMT75
ACTMT75
ACTMT75
ACTMT75
ACTMT75
ACTMT75
ACTMT75
ACTMT75
ACTWR25
ACTWR25
ACTWR25
PCIP10
PCIP10
PCIP10
PCIP11
PCIP11
PCIP11
PCIP11
PCIP11
PCIP11
PCIP11
PCIP12
PCIP12
PCIP12
PCIP12
PCIP12
PCIP12
PCIP12
PCIP12
PCIP12
PCIP13
PCIP13
PCIP13
PCIP13
PCIP13
PCIP13
PCIP13
PCIP13
PCIP13
OVERALL_YR8_N
OVERALL_YR8_N
OVERALL_YR8_N
OVERALL_YR8_N
OVERALL_YR8_N
OVERALL_YR8_N
OVERALL_YR8_N
OVERALL_YR8_N
OVERALL_YR8_N
LO_INC_YR8_N
LO_INC_YR8_N
LO_INC_YR8_N
LO_INC_YR8_N
LO_INC_YR8_N
LO_INC_YR8_N
LO_INC_YR8_N
LO_INC_YR8_N
LO_INC_YR8_N
MD_INC_YR8_N
MD_INC_YR8_N
MD_INC_YR8_N
MD_INC_YR8_N
MD_INC_YR8_N
MD_INC_YR8_N
MD_INC_YR8_N
MD_INC_YR8_N
MD_INC_YR8_N
HI_INC_YR8_N
HI_INC_YR8_N
HI_INC_YR8_N
HI_INC_YR8_N
HI_INC_YR8_N
HI_INC_YR8_N
HI_INC_YR8_N
HI_INC_YR8_N
HI_INC_YR8_N
DEP_YR8_N
DEP_YR8_N
DEP_YR8_N
DEP_YR8_N
DEP_YR8_N
DEP_YR8_N
DEP_YR8_N
DEP_YR8_N
DEP_YR8_N
IND_YR8_N
IND_YR8_N
IND_YR8_N
IND_YR8_N
IND_YR8_N
IND_YR8_N
IND_YR8_N
IND_YR8_N
IND_YR8_N
FEMALE_YR8_N
FEMALE_YR8_N
FEMALE_YR8_N
FEMALE_YR8_N
FEMALE_YR8_N
FEMALE_YR8_N
FEMALE_YR8_N
FEMALE_YR8_N
FEMALE_YR8_N
MALE_YR8_N
MALE_YR8_N
MALE_YR8_N
MALE_YR8_N
MALE_YR8_N
MALE_YR8_N
MALE_YR8_N
MALE_YR8_N
MALE_YR8_N
PELL_YR8_N
PELL_YR8_N
PELL_YR8_N
PELL_YR8_N
PELL_YR8_N
PELL_YR8_N
PELL_YR8_N
PELL_YR8_N
PELL_YR8_N
NOPELL_YR8_N
NOPELL_YR8_N
NOPELL_YR8_N
NOPELL_YR8_N
NOPELL_YR8_N
NOPELL_YR8_N
NOPELL_YR8_N
NOPELL_YR8_N
NOPELL_YR8_N
LOAN_YR8_N
LOAN_YR8_N
LOAN_YR8_N
LOAN_YR8_N
LOAN_YR8_N
LOAN_YR8_N
LOAN_YR8_N
LOAN_YR8_N
LOAN_YR8_N
NOLOAN_YR8_N
NOLOAN_YR8_N
NOLOAN_YR8_N
NOLOAN_YR8_N
NOLOAN_YR8_N
NOLOAN_YR8_N
NOLOAN_YR8_N
NOLOAN_YR8_N
NOLOAN_YR8_N
FIRSTGEN_YR8_N
FIRSTGEN_YR8_N
FIRSTGEN_YR8_N
FIRSTGEN_YR8_N
FIRSTGEN_YR8_N
FIRSTGEN_YR8_N
FIRSTGEN_YR8_N
FIRSTGEN_YR8_N
FIRSTGEN_YR8_N
NOT1STGEN_YR8_N
NOT1STGEN_YR8_N
NOT1STGEN_YR8_N
NOT1STGEN_YR8_N
NOT1STGEN_YR8_N
NOT1STGEN_YR8_N
NOT1STGEN_YR8_N
NOT1STGEN_YR8_N
NOT1STGEN_YR8_N
DEBT_MDN
DEBT_MDN
DEBT_MDN
DEBT_MDN
DEBT_MDN
DEBT_MDN
DEBT_MDN
DEBT_MDN
DEBT_MDN
GRAD_DEBT_MDN
GRAD_DEBT_MDN
GRAD_DEBT_MDN
GRAD_DEBT_MDN
GRAD_DEBT_MDN
GRAD_DEBT_MDN
GRAD_DEBT_MDN
GRAD_DEBT_MDN
GRAD_DEBT_MDN
WDRAW_DEBT_MDN
WDRAW_DEBT_MDN
WDRAW_DEBT_MDN
WDRAW_DEBT_MDN
WDRAW_DEBT_MDN
WDRAW_DEBT_MDN
WDRAW_DEBT_MDN
WDRAW_DEBT_MDN
WDRAW_DEBT_MDN
LO_INC_DEBT_MDN
LO_INC_DEBT_MDN
LO_INC_DEBT_MDN
LO_INC_DEBT_MDN
LO_INC_DEBT_MDN
LO_INC_DEBT_MDN
LO_INC_DEBT_MDN
LO_INC_DEBT_MDN
LO_INC_DEBT_MDN
MD_INC_DEBT_MDN
MD_INC_DEBT_MDN
MD_INC_DEBT_MDN
MD_INC_DEBT_MDN
MD_INC_DEBT_MDN
MD_INC_DEBT_MDN
MD_INC_DEBT_MDN
MD_INC_DEBT_MDN
MD_INC_DEBT_MDN
HI_INC_DEBT_MDN
HI_INC_DEBT_MDN
HI_INC_DEBT_MDN
HI_INC_DEBT_MDN
HI_INC_DEBT_MDN
HI_INC_DEBT_MDN
HI_INC_DEBT_MDN
HI_INC_DEBT_MDN
HI_INC_DEBT_MDN
DEP_DEBT_MDN
DEP_DEBT_MDN
DEP_DEBT_MDN
DEP_DEBT_MDN
DEP_DEBT_MDN
DEP_DEBT_MDN
DEP_DEBT_MDN
DEP_DEBT_MDN
DEP_DEBT_MDN
IND_DEBT_MDN
IND_DEBT_MDN
IND_DEBT_MDN
IND_DEBT_MDN
IND_DEBT_MDN
IND_DEBT_MDN
IND_DEBT_MDN
IND_DEBT_MDN
IND_DEBT_MDN
PELL_DEBT_MDN
PELL_DEBT_MDN
PELL_DEBT_MDN
PELL_DEBT_MDN
PELL_DEBT_MDN
PELL_DEBT_MDN
PELL_DEBT_MDN
PELL_DEBT_MDN
PELL_DEBT_MDN
NOPELL_DEBT_MDN
NOPELL_DEBT_MDN
NOPELL_DEBT_MDN
NOPELL_DEBT_MDN
NOPELL_DEBT_MDN
NOPELL_DEBT_MDN
NOPELL_DEBT_MDN
NOPELL_DEBT_MDN
NOPELL_DEBT_MDN
FEMALE_DEBT_MDN
FEMALE_DEBT_MDN
FEMALE_DEBT_MDN
FEMALE_DEBT_MDN
FEMALE_DEBT_MDN
FEMALE_DEBT_MDN
FEMALE_DEBT_MDN
FEMALE_DEBT_MDN
FEMALE_DEBT_MDN
MALE_DEBT_MDN
MALE_DEBT_MDN
MALE_DEBT_MDN
MALE_DEBT_MDN
MALE_DEBT_MDN
MALE_DEBT_MDN
MALE_DEBT_MDN
MALE_DEBT_MDN
MALE_DEBT_MDN
FIRSTGEN_DEBT_MDN
FIRSTGEN_DEBT_MDN
FIRSTGEN_DEBT_MDN
FIRSTGEN_DEBT_MDN
FIRSTGEN_DEBT_MDN
FIRSTGEN_DEBT_MDN
FIRSTGEN_DEBT_MDN
FIRSTGEN_DEBT_MDN
FIRSTGEN_DEBT_MDN
ACTWR25
ACTWR25
ACTWR25
PCIP10
PCIP10
PCIP10
ACTWR25
ACTWR25
ACTWR25
PCIP10
PCIP10
PCIP10
PCIP11
PCIP11
PCIP11
PCIP11
PCIP11
PCIP11
PCIP11

{'ACTEN75': 0,
 'ACTMT25': 0,
 'ACTMT75': 0,
 'ACTWR25': 0,
 'ACTWR75': 0,
 'ACTCMMID': 0,
 'ACTENMID': 0,
 'ACTMTMID': 0,
 'ACTWRMID': 0,
 'SAT_AVG': 0,
 'SAT_AVG_ALL': 0,
 'PCIP01': 0,
 'PCIP03': 0,
 'PCIP04': 0,
 'PCIP05': 0,
 'PCIP09': 0,
 'PCIP10': 0,
 'PCIP11': 0,
 'PCIP12': 0,
 'PCIP13': 0,
 'OVERALL_YR8_N': 0,
 'LO_INC_YR8_N': 0,
 'MD_INC_YR8_N': 0,
 'HI_INC_YR8_N': 0,
 'DEP_YR8_N': 0,
 'IND_YR8_N': 0,
 'FEMALE_YR8_N': 0,
 'MALE_YR8_N': 0,
 'PELL_YR8_N': 0,
 'NOPELL_YR8_N': 0,
 'LOAN_YR8_N': 0,
 'NOLOAN_YR8_N': 0,
 'FIRSTGEN_YR8_N': 0,
 'NOT1STGEN_YR8_N': 0,
 'DEBT_MDN': 0,
 'GRAD_DEBT_MDN': 0,
 'WDRAW_DEBT_MDN': 0,
 'LO_INC_DEBT_MDN': 0,
 'MD_INC_DEBT_MDN': 0,
 'HI_INC_DEBT_MDN': 0,
 'DEP_DEBT_MDN': 0,
 'IND_DEBT_MDN': 0,
 'PELL_DEBT_MDN': 0,
 'NOPELL_DEBT_MDN': 0,
 'FEMALE_DEBT_MDN': 0,
 'MALE_DEBT_MDN': 0,
 'FIRSTGEN_DEBT_MDN': 0}

In [193]:
null_count

{}

In [212]:
z[0][0]

'ACTEN75'

In [220]:
n_c={}
for i in range(0,4):
    for j in range(len(z[i])):
        if z[i][j]  not in list_null_col1:
            n_c.update({z[i][j]:1})
n_c

{'ACTEN75': 1,
 'ACTMT25': 1,
 'ACTMT75': 1,
 'ACTWR25': 1,
 'PCIP10': 1,
 'PCIP11': 1,
 'PCIP12': 1,
 'PCIP13': 1,
 'OVERALL_YR8_N': 1,
 'LO_INC_YR8_N': 1,
 'MD_INC_YR8_N': 1,
 'HI_INC_YR8_N': 1,
 'DEP_YR8_N': 1,
 'IND_YR8_N': 1,
 'FEMALE_YR8_N': 1,
 'MALE_YR8_N': 1,
 'PELL_YR8_N': 1,
 'NOPELL_YR8_N': 1,
 'LOAN_YR8_N': 1,
 'NOLOAN_YR8_N': 1,
 'FIRSTGEN_YR8_N': 1,
 'NOT1STGEN_YR8_N': 1,
 'DEBT_MDN': 1,
 'GRAD_DEBT_MDN': 1,
 'WDRAW_DEBT_MDN': 1,
 'LO_INC_DEBT_MDN': 1,
 'MD_INC_DEBT_MDN': 1,
 'HI_INC_DEBT_MDN': 1,
 'DEP_DEBT_MDN': 1,
 'IND_DEBT_MDN': 1,
 'PELL_DEBT_MDN': 1,
 'NOPELL_DEBT_MDN': 1,
 'FEMALE_DEBT_MDN': 1,
 'MALE_DEBT_MDN': 1,
 'FIRSTGEN_DEBT_MDN': 1}