In [1]:
import pandas as pd
import numpy as np

In [2]:
#Loading all data frames into our python notebook

data78 = pd.read_csv('data78.csv', low_memory=False)
data89 = pd.read_csv('data89.csv', low_memory=False)
data910 = pd.read_csv('data910.csv', low_memory=False)
data1011 = pd.read_csv('data1011.csv', low_memory=False)
data1112 = pd.read_csv('data1112.csv', low_memory=False)
data1213 = pd.read_csv('data1213.csv', low_memory=False)
data1314 = pd.read_csv('data1314.csv', low_memory=False)
data1415 = pd.read_csv('data1415.csv', low_memory=False)
data1516 = pd.read_csv('data1516.csv', low_memory=False)
data1617 = pd.read_csv('data1617.csv', low_memory=False)

In [3]:
#loading column dictionary

cnames=pd.read_csv('c_name.csv')

In [14]:
#taking our column names from the dictionary and converting it to a list

c_list=cnames['column name'].values.tolist()
c_list2=c_list
len(c_list)

280

In [5]:
#Extracting all the column names that we require

def select_columns(df):
    df = df[[c for c in df.columns if c in c_list]]
    return df

data1 = select_columns(data78)
data2 = select_columns(data89)
data3 = select_columns(data910)
data4 = select_columns(data1011)
data5 = select_columns(data1112)
data6 = select_columns(data1213)
data7 = select_columns(data1314)
data8 = select_columns(data1415)
data9 = select_columns(data1516)
data10 = select_columns(data1617)

In [7]:
# for x in range(1,11):
list_null_col= []

def create_null_list(df):
    df_na= df.isna()
    count_true=0
    count_false=0
    for c in c_list:
#     print(c)
        col= list(df_na[c])
        for r in col:
            if r == True:
                count_true+=1
    #             print(count_true)
            else:
                count_false+=1
        if count_true >= count_false:
            list_null_col.append(c)     #List with all columns with more number of null values

In [10]:
len(list_null_col)

169

In [9]:
#Creating a list of column names with more number of null values across entire data set. 


list_df=[data1,data2,data3,data4,data5,data6,data7,data8,data9,data10]
for x in list_df:
    create_null_list(x)
    
list_null_col
# len(list_null_col)

['ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'ACTEN75',
 'ACTMT25',
 'ACTMT75',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP12',
 'PCIP13',
 'OVERALL_YR8_N',
 'LO_INC_YR8_N',
 'MD_INC_YR8_N',
 'HI_INC_YR8_N',
 'DEP_YR8_N',
 'IND_YR8_N',
 'FEMALE_YR8_N',
 'MALE_YR8_N',
 'PELL_YR8_N',
 'NOPELL_YR8_N',
 'LOAN_YR8_N',
 'NOLOAN_YR8_N',
 'FIRSTGEN_YR8_N',
 'NOT1STGEN_YR8_N',
 'DEBT_MDN',
 'GRAD_DEBT_MDN',
 'WDRAW_DEBT_MDN',
 'LO_INC_DEBT_MDN',
 'MD_INC_DEBT_MDN',
 'HI_INC_DEBT_MDN',
 'DEP_DEBT_MDN',
 'IND_DEBT_MDN',
 'PELL_DEBT_MDN',
 'NOPELL_DEBT_MDN',
 'FEMALE_DEBT_MDN',
 'MALE_DEBT_MDN',
 'FIRSTGEN_DEBT_MDN']

In [11]:
#Converting list into a numpy array to find unique column names, then converting it back to a list

arr_null_col=np.array(list_null_col)
list_null_col_unique=list(np.unique(arr_null_col))
print(len(list_null_col_unique))

47

In [12]:
d_null_col_count={}
for col in list_null_col_unique:
    d_null_col_count[col]=list_null_col.count(col)
d_null_col_count

{'ACTCMMID': 10,
 'ACTEN75': 1,
 'ACTENMID': 10,
 'ACTMT25': 1,
 'ACTMT75': 1,
 'ACTMTMID': 10,
 'ACTWR25': 7,
 'ACTWR75': 10,
 'ACTWRMID': 10,
 'DEBT_MDN': 1,
 'DEP_DEBT_MDN': 1,
 'DEP_YR8_N': 1,
 'FEMALE_DEBT_MDN': 1,
 'FEMALE_YR8_N': 1,
 'FIRSTGEN_DEBT_MDN': 1,
 'FIRSTGEN_YR8_N': 1,
 'GRAD_DEBT_MDN': 1,
 'HI_INC_DEBT_MDN': 1,
 'HI_INC_YR8_N': 1,
 'IND_DEBT_MDN': 1,
 'IND_YR8_N': 1,
 'LOAN_YR8_N': 1,
 'LO_INC_DEBT_MDN': 1,
 'LO_INC_YR8_N': 1,
 'MALE_DEBT_MDN': 1,
 'MALE_YR8_N': 1,
 'MD_INC_DEBT_MDN': 1,
 'MD_INC_YR8_N': 1,
 'NOLOAN_YR8_N': 1,
 'NOPELL_DEBT_MDN': 1,
 'NOPELL_YR8_N': 1,
 'NOT1STGEN_YR8_N': 1,
 'OVERALL_YR8_N': 1,
 'PCIP01': 10,
 'PCIP03': 10,
 'PCIP04': 10,
 'PCIP05': 10,
 'PCIP09': 10,
 'PCIP10': 7,
 'PCIP11': 3,
 'PCIP12': 1,
 'PCIP13': 1,
 'PELL_DEBT_MDN': 1,
 'PELL_YR8_N': 1,
 'SAT_AVG': 10,
 'SAT_AVG_ALL': 10,
 'WDRAW_DEBT_MDN': 1}

In [13]:
final_na_col_list= []
keys= list(d_null_col_count.keys())
for k in keys:
    if d_null_col_count[k] != 1:
        final_na_col_list.append(k)
print(len(final_na_col_list))     # final list with columns having null values present in multiple dataframes

15

In [17]:
for x in final_na_col_list:
    c_list.remove(x)
len(c_list)

265

In [18]:
#Extracting all the column names that we require

def select_columns(df):
    df = df[[c for c in df.columns if c in c_list]]
    return df

data1_2 = select_columns(data78)
data2_2 = select_columns(data89)
data3_2 = select_columns(data910)
data4_2 = select_columns(data1011)
data5_2 = select_columns(data1112)
data6_2 = select_columns(data1213)
data7_2 = select_columns(data1314)
data8_2 = select_columns(data1415)
data9_2 = select_columns(data1516)
data10_2 = select_columns(data1617)

In [26]:
data1_2.head()

0    100654
1    100663
2    100690
3    100706
4    100724
Name: UNITID, dtype: int64

In [23]:
for x in c_list:
    data1_2[x]=data1_2[x].fillna(0)

KeyError: 'UNITID'

In [24]:
data1_2.fillna(0)

0         100654
1         100663
2         100690
3         100706
4         100724
5         100751
6         100760
7         100812
8         100830
9         100858
10        100937
11        101028
12        101073
13        101116
14        101143
15        101161
16        101189
17        101240
18        101286
19        101295
20        101301
21        101365
22        101435
23        101453
24        101462
25        101480
26        101499
27        101505
28        101514
29        101541
          ...
6860    22797902
6861    22828201
6862    23059701
6863    23384201
6864    23693901
6865    23693902
6866    23693903
6867    23797801
6868    24366501
6869    24603501
6870    37564701
6871    37728101
6872    38561901
6873    38561902
6874    40280001
6875    40620001
6876    40620002
6877    40884401
6878    40884402
6879    42312001
6880    42817001
6881    42817002
6882    43821201
6883    43821202
6884    43821203
6885    44098901
6886    44098902
6887    44098903
6888    44098904
6889    44098905
Name: UNITID, Length: 6890, dtype: int64

In [25]:
data1_2.head()

0    100654
1    100663
2    100690
3    100706
4    100724
Name: UNITID, dtype: int64

In [33]:
data4_2.dropna(axis=1, thresh=6000)

,UNITID,INSTNM,CITY,STABBR,ZIP,SCH_DEG,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,...,MN_EARN_WNE_P9,SD_EARN_WNE_P9,GT_25K_P9,DEBT_MDN_SUPP,GRAD_DEBT_MDN_SUPP,ICLEVEL,UGDS_MEN,UGDS_WOMEN,CDR2_DENOM,OPENADMP
0,100654,Alabama A & M University,Normal,AL,35762,3.0,1,1,3,4,...,33800,27500,0.58783781528472,11346,24449.5,1,0.4771,0.5229,1515.0,2.0
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,3.0,1,1,3,4,...,44500,38600,0.73726850748062,9285.5,15250,1,0.4170,0.5830,2842.0,2.0
2,100690,Amridge University,Montgomery,AL,36117-3553,3.0,1,1,3,4,...,42400,30500,0.7356321811676,9500,17533,1,0.4649,0.5351,316.0,2.0
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,3.0,1,1,3,4,...,50200,37700,0.78119349479675,10173,18725,1,0.5297,0.4703,1085.0,2.0
4,100724,Alabama State University,Montgomery,AL,36104-0271,3.0,1,1,3,4,...,29400,20000,0.52983427047729,8663,24728,1,0.4097,0.5903,2054.0,2.0
5,100751,The University of Alabama,Tuscaloosa,AL,35487-0166,3.0,1,1,3,4,...,47200,49300,0.77460408210754,12500,20000,1,0.4763,0.5237,3629.0,2.0
6,100760,Central Alabama Community College,Alexander City,AL,35010,2.0,1,1,2,2,...,29400,21800,0.52394777536392,5500,11544.5,2,0.3533,0.6467,427.0,1.0
7,100812,Athens State University,Athens,AL,35611,3.0,1,1,3,3,...,42100,24500,0.78364115953445,10000,16582,1,0.3439,0.6561,744.0,NaN
8,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,3.0,1,1,3,4,...,35500,30300,0.6590524315834,7160,17598,1,0.3787,0.6213,1265.0,2.0
9,100858,Auburn University,Auburn,AL,36849,3.0,1,1,3,4,...,49700,45900,0.80004858970642,12875,PrivacySuppressed,1,0.5142,0.4858,3015.0,2.0
10,100937,Birmingham Southern College,Birmingham,AL,35254,3.0,1,1,3,4,...,44700,27600,0.76890754699707,15000,PrivacySuppressed,1,0.5062,0.4938,180.0,2.0
11,101028,Chattahoochee Valley Community College,Phenix City,AL,36869,2.0,1,1,2,2,...,30200,21700,0.55839997529983,3500,3500,2,0.3509,0.6491,327.0,1.0
12,101073,Concordia College Alabama,Selma,AL,36701,3.0,1,1,3,3,...,23000,15800,0.35214447975158,3500,8250,1,0.5690,0.4310,72.0,1.0
13,101116,South University-Montgomery,Montgomery,AL,36116,3.0,0,8,2,4,...,34900,27200,0.60914582014083,6000,24627,1,0.2738,0.7262,7338.0,2.0
14,101143,Enterprise State Community College,Enterprise,AL,36330-1300,2.0,1,1,1,2,...,29000,21600,0.51152074337005,3500,PrivacySuppressed,2,0.6071,0.3929,257.0,1.0
15,101161,Coastal Alabama Community College,Bay Minette,AL,36507-2698,2.0,1,1,2,2,...,31300,22000,0.56340581178665,3500,6000,2,0.3674,0.6326,702.0,1.0
16,101189,Faulkner University,Montgomery,AL,36109-3390,3.0,1,1,3,4,...,42500,30500,0.70171338319778,11078.5,PrivacySuppressed,1,0.3770,0.6230,1168.0,2.0
17,101240,Gadsden State Community College,Gadsden,AL,35903,2.0,1,1,2,2,...,29000,20000,0.51573675870895,PrivacySuppressed,PrivacySuppressed,2,0.3783,0.6217,0.0,1.0
18,101286,George C Wallace Community College-Dothan,Dothan,AL,36303-9234,2.0,1,1,2,2,...,30700,23500,0.50740963220596,PrivacySuppressed,PrivacySuppressed,2,0.3199,0.6801,1.0,1.0
19,101295,George C Wallace State Community College-Hance...,Hanceville,AL,35077-2000,2.0,1,1,2,2,...,30100,20500,0.54213482141494,4000,7500,2,0.3700,0.6300,1022.0,1.0
20,101301,George C Wallace State Community College-Selma,Selma,AL,36703-2808,2.0,1,1,2,2,...,27300,20100,0.44327175617218,PrivacySuppressed,PrivacySuppressed,2,0.3213,0.6787,0.0,1.0
21,101365,Herzing University-Birmingham,Birmingham,AL,35209,2.0,0,11,2,3,...,41700,24600,0.73429954051971,6375,18627,1,0.3245,0.6755,2666.0,2.0
22,101435,Huntingdon College,Montgomery,AL,36106-2148,3.0,1,1,3,3,...,37700,27000,0.66063350439071,12000,23000,1,0.4909,0.5091,235.0,2.0
23,101453,Heritage Christian University,Florence,AL,35630-9977,3.0,1,1,3,4,...,45800,92800,0.60000002384185,PrivacySuppressed,PrivacySuppressed,1,0.8000,0.2000,22.0,1.0
24,101462,J. F. Drake State Community and Technical College,Huntsville,AL,35811,1.0,1,1,1,2,...,26400,20000,0.48447203636169,PrivacySuppressed,PrivacySuppressed,2,0.3801,0.6199,0.0,1.0
25,101480,Jacksonville State University,Jacksonville,AL,36265,3.0,1,1,3,4,...,35800,23200,0.6611533164978,9250,18000,1,0.4244,0.5756,2145.0,2.0
26,101499,Jefferson Davis Community College,Brewton,AL,36426,2.0,1,1,2,2,...,30700,23200,0.54075545072555,PrivacySuppressed,PrivacySuppressed,2,0.4018,0.5982,0.0,1.0
27,101505,Jefferson State Community College,Birmingham,AL,35215-3098,2.0,1,1,2,2,...,32100,22200,0.58726900815963,3500,5750,2,0.3954,0.6046,818.0,1.0
28,101514,John C Calhoun State Community College,Tanner,AL,35671,2.0,1,1,2,2,...,30800,22900,0.53264605998992,3500,6500,2,0.4389,0.5611,1263.0,1.0
29,101541,Judson College,Marion,AL,36756,3.0,1,1,3,3,...,32000,21100,0.60305345058441,9500,21250,1,0.0290,0.9710,92.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7384,45057102,Rasmussen College-Wausau,Wausau,WI,544017804,2.0,0,20,0,0,...,33500,20600,0.66117972135543,6334,16328.5,1,NaN,NaN,2239.0,NaN
7385,45312701,Strayer University-Louisville Campus,Louisville,KY,40223,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7386,45312702,Strayer University-Florence Campus,Florence,KY,41042,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7387,45316301,Strayer University-North Charlotte,Charlotte,NC,28027,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7388,45316302,Strayer University-South Charlotte,Charlotte,NC,28273,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7389,45316303,Strayer University-North Raleigh Campus,Raleigh,NC,27616,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7390,45316304,Strayer University-Greensboro Campus,Greensboro,NC,27407,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7391,45316305,Strayer University-Huntersville Campus,Raleigh,NC,28078,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7392,45316306,Strayer University-South Raleigh Campus,Raleigh,NC,27603,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7393,45321501,Strayer University-Willingboro Campus,Willingboro,NJ,08046,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7394,45321502,Strayer University-Lawrenceville,Lawrenceville,NJ,08648,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7395,45321503,Strayer University-Piscataway,Piscataway,NJ,08854,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7396,45666701,Strayer University-Columbus Campus,Columbus,OH,43240,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7397,45666702,Strayer University-Fairview Park Campus,Fairview Park,OH,44126,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7398,45666703,Strayer University-Akron Campus,Akron,OH,44320,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7399,45786401,Finger Lakes School of Massage,Mt. Kisco,NY,10549,1.0,0,2,0,0,...,NaN,NaN,NaN,9500,PrivacySuppressed,3,NaN,NaN,NaN,NaN
7400,45891901,Strayer University-Cobb Campus,Atlanta,GA,30339,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7401,45891902,Strayer University-Morrow Campus,Morrow,GA,30260,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7402,45891903,Strayer University-Roswell Campus,Roswell,GA,30076,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7403,45891904,Strayer University-Douglasville Campus,Douglasville,GA,30135,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7404,45891905,Strayer University-Lithonia Campus,Lithonia,GA,30038,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7405,45891906,Strayer University-Savannah Campus,Savannah,GA,31419,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7406,45891907,Strayer University-Augusta Campus,Augusta,GA,30909,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7407,45891908,Strayer University-Columbus,Columbus,GA,31909,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7408,45896401,Strayer University-Columbia Campus,Columbia,SC,29210,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7409,45896402,Strayer University-Charleston Campus,North Charleston,SC,29418,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7410,45897301,Strayer University-Irving,Irving,TX,75063,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7411,45897302,Strayer University-Katy,Houston,TX,77079,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7412,45897303,Strayer University-Northwest Houston,Houston,TX,77064,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN
7413,45897304,Strayer University-Plano,Plano,TX,75093,3.0,0,85,0,0,...,56100,37500,0.78874593973159,6461,21945,1,NaN,NaN,12110.0,NaN

In [32]:
data4_2

,UNITID,INSTNM,CITY,STABBR,ZIP,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,...,DTRANS_4,TRANS_L4,DTRANS_L4,ICLEVEL,UGDS_MEN,UGDS_WOMEN,CDR2_DENOM,OPENADMP,UGNONDS,GRADS
0,100654,Alabama A & M University,Normal,AL,35762,3.0,NaN,1,1,3,...,1198.0,NaN,NaN,1,0.4771,0.5229,1515.0,2.0,10.0,874.0
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,3.0,NaN,1,1,3,...,1536.0,NaN,NaN,1,0.4170,0.5830,2842.0,2.0,367.0,6515.0
2,100690,Amridge University,Montgomery,AL,36117-3553,3.0,NaN,1,1,3,...,13.0,NaN,NaN,1,0.4649,0.5351,316.0,2.0,NaN,379.0
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,3.0,NaN,1,1,3,...,653.0,NaN,NaN,1,0.5297,0.4703,1085.0,2.0,177.0,1609.0
4,100724,Alabama State University,Montgomery,AL,36104-0271,3.0,NaN,1,1,3,...,1138.0,NaN,NaN,1,0.4097,0.5903,2054.0,2.0,NaN,823.0
5,100751,The University of Alabama,Tuscaloosa,AL,35487-0166,3.0,NaN,1,1,3,...,3290.0,NaN,NaN,1,0.4763,0.5237,3629.0,2.0,506.0,5245.0
6,100760,Central Alabama Community College,Alexander City,AL,35010,2.0,NaN,1,1,2,...,NaN,0.313063,444.0,2,0.3533,0.6467,427.0,1.0,106.0,NaN
7,100812,Athens State University,Athens,AL,35611,3.0,NaN,1,1,3,...,NaN,NaN,NaN,1,0.3439,0.6561,744.0,NaN,207.0,NaN
8,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,3.0,NaN,1,1,3,...,611.0,NaN,NaN,1,0.3787,0.6213,1265.0,2.0,13.0,988.0
9,100858,Auburn University,Auburn,AL,36849,3.0,NaN,1,1,3,...,3579.0,NaN,NaN,1,0.5142,0.4858,3015.0,2.0,NaN,4857.0
10,100937,Birmingham Southern College,Birmingham,AL,35254,3.0,NaN,1,1,3,...,367.0,NaN,NaN,1,0.5062,0.4938,180.0,2.0,NaN,21.0
11,101028,Chattahoochee Valley Community College,Phenix City,AL,36869,2.0,NaN,1,1,2,...,NaN,0.113281,256.0,2,0.3509,0.6491,327.0,1.0,178.0,NaN
12,101073,Concordia College Alabama,Selma,AL,36701,3.0,NaN,1,1,3,...,247.0,NaN,NaN,1,0.5690,0.4310,72.0,1.0,NaN,NaN
13,101116,South University-Montgomery,Montgomery,AL,36116,3.0,NaN,0,8,2,...,33.0,NaN,NaN,1,0.2738,0.7262,7338.0,2.0,NaN,57.0
14,101143,Enterprise State Community College,Enterprise,AL,36330-1300,2.0,NaN,1,1,1,...,NaN,0.222482,427.0,2,0.6071,0.3929,257.0,1.0,361.0,NaN
15,101161,Coastal Alabama Community College,Bay Minette,AL,36507-2698,2.0,NaN,1,1,2,...,NaN,0.355172,870.0,2,0.3674,0.6326,702.0,1.0,175.0,NaN
16,101189,Faulkner University,Montgomery,AL,36109-3390,3.0,NaN,1,1,3,...,185.0,NaN,NaN,1,0.3770,0.6230,1168.0,2.0,228.0,564.0
17,101240,Gadsden State Community College,Gadsden,AL,35903,2.0,NaN,1,1,2,...,NaN,0.178938,1168.0,2,0.3783,0.6217,0.0,1.0,299.0,NaN
18,101286,George C Wallace Community College-Dothan,Dothan,AL,36303-9234,2.0,NaN,1,1,2,...,NaN,0.230878,706.0,2,0.3199,0.6801,1.0,1.0,291.0,NaN
19,101295,George C Wallace State Community College-Hance...,Hanceville,AL,35077-2000,2.0,NaN,1,1,2,...,NaN,0.168094,934.0,2,0.3700,0.6300,1022.0,1.0,396.0,NaN
20,101301,George C Wallace State Community College-Selma,Selma,AL,36703-2808,2.0,NaN,1,1,2,...,NaN,0.141667,360.0,2,0.3213,0.6787,0.0,1.0,255.0,NaN
21,101365,Herzing University-Birmingham,Birmingham,AL,35209,2.0,NaN,0,11,2,...,25.0,NaN,NaN,1,0.3245,0.6755,2666.0,2.0,1.0,NaN
22,101435,Huntingdon College,Montgomery,AL,36106-2148,3.0,NaN,1,1,3,...,192.0,NaN,NaN,1,0.4909,0.5091,235.0,2.0,13.0,NaN
23,101453,Heritage Christian University,Florence,AL,35630-9977,3.0,NaN,1,1,3,...,3.0,NaN,NaN,1,0.8000,0.2000,22.0,1.0,NaN,28.0
24,101462,J. F. Drake State Community and Technical College,Huntsville,AL,35811,1.0,NaN,1,1,1,...,NaN,0.052239,134.0,2,0.3801,0.6199,0.0,1.0,310.0,NaN
25,101480,Jacksonville State University,Jacksonville,AL,36265,3.0,NaN,1,1,3,...,1017.0,NaN,NaN,1,0.4244,0.5756,2145.0,2.0,353.0,1404.0
26,101499,Jefferson Davis Community College,Brewton,AL,36426,2.0,NaN,1,1,2,...,NaN,0.078947,304.0,2,0.4018,0.5982,0.0,1.0,57.0,NaN
27,101505,Jefferson State Community College,Birmingham,AL,35215-3098,2.0,NaN,1,1,2,...,NaN,0.285558,914.0,2,0.3954,0.6046,818.0,1.0,1135.0,NaN
28,101514,John C Calhoun State Community College,Tanner,AL,35671,2.0,NaN,1,1,2,...,NaN,0.246426,1189.0,2,0.4389,0.5611,1263.0,1.0,970.0,NaN
29,101541,Judson College,Marion,AL,36756,3.0,NaN,1,1,3,...,69.0,NaN,NaN,1,0.0290,0.9710,92.0,2.0,12.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7384,45057102,Rasmussen College-Wausau,Wausau,WI,544017804,2.0,NaN,0,20,0,...,NaN,NaN,NaN,1,NaN,NaN,2239.0,NaN,NaN,NaN
7385,45312701,Strayer University-Louisville Campus,Louisville,KY,40223,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7386,45312702,Strayer University-Florence Campus,Florence,KY,41042,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7387,45316301,Strayer University-North Charlotte,Charlotte,NC,28027,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7388,45316302,Strayer University-South Charlotte,Charlotte,NC,28273,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7389,45316303,Strayer University-North Raleigh Campus,Raleigh,NC,27616,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7390,45316304,Strayer University-Greensboro Campus,Greensboro,NC,27407,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7391,45316305,Strayer University-Huntersville Campus,Raleigh,NC,28078,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7392,45316306,Strayer University-South Raleigh Campus,Raleigh,NC,27603,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7393,45321501,Strayer University-Willingboro Campus,Willingboro,NJ,08046,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7394,45321502,Strayer University-Lawrenceville,Lawrenceville,NJ,08648,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7395,45321503,Strayer University-Piscataway,Piscataway,NJ,08854,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7396,45666701,Strayer University-Columbus Campus,Columbus,OH,43240,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7397,45666702,Strayer University-Fairview Park Campus,Fairview Park,OH,44126,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7398,45666703,Strayer University-Akron Campus,Akron,OH,44320,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7399,45786401,Finger Lakes School of Massage,Mt. Kisco,NY,10549,1.0,NaN,0,2,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
7400,45891901,Strayer University-Cobb Campus,Atlanta,GA,30339,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7401,45891902,Strayer University-Morrow Campus,Morrow,GA,30260,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7402,45891903,Strayer University-Roswell Campus,Roswell,GA,30076,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7403,45891904,Strayer University-Douglasville Campus,Douglasville,GA,30135,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7404,45891905,Strayer University-Lithonia Campus,Lithonia,GA,30038,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7405,45891906,Strayer University-Savannah Campus,Savannah,GA,31419,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7406,45891907,Strayer University-Augusta Campus,Augusta,GA,30909,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7407,45891908,Strayer University-Columbus,Columbus,GA,31909,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7408,45896401,Strayer University-Columbia Campus,Columbia,SC,29210,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7409,45896402,Strayer University-Charleston Campus,North Charleston,SC,29418,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7410,45897301,Strayer University-Irving,Irving,TX,75063,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7411,45897302,Strayer University-Katy,Houston,TX,77079,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7412,45897303,Strayer University-Northwest Houston,Houston,TX,77064,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN
7413,45897304,Strayer University-Plano,Plano,TX,75093,3.0,NaN,0,85,0,...,NaN,NaN,NaN,1,NaN,NaN,12110.0,NaN,NaN,NaN

In [35]:
data5_2

,UNITID,INSTNM,CITY,STABBR,ZIP,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,...,DTRANS_4,TRANS_L4,DTRANS_L4,ICLEVEL,UGDS_MEN,UGDS_WOMEN,CDR2_DENOM,OPENADMP,UGNONDS,GRADS
0,100654,Alabama A & M University,Normal,AL,35762,3.0,NaN,1,1,3,...,1088.0,NaN,NaN,1,0.4786,0.5214,1438.0,2.0,16.0,794.0
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,3.0,NaN,1,1,3,...,1515.0,NaN,NaN,1,0.4154,0.5846,3160.0,2.0,274.0,6447.0
2,100690,Amridge University,Montgomery,AL,36117-3553,3.0,NaN,1,1,3,...,4.0,NaN,NaN,1,0.4389,0.5611,266.0,1.0,NaN,415.0
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,3.0,NaN,1,1,3,...,626.0,NaN,NaN,1,0.5402,0.4598,1208.0,2.0,180.0,1694.0
4,100724,Alabama State University,Montgomery,AL,36104-0271,3.0,NaN,1,1,3,...,1198.0,NaN,NaN,1,0.4054,0.5946,1957.0,2.0,24.0,682.0
5,100751,The University of Alabama,Tuscaloosa,AL,35487-0166,3.0,NaN,1,1,3,...,3642.0,NaN,NaN,1,0.4677,0.5323,3931.0,2.0,621.0,5413.0
6,100760,Central Alabama Community College,Alexander City,AL,35010,2.0,NaN,1,1,2,...,NaN,0.408072,446.0,2,0.3435,0.6565,430.0,1.0,113.0,NaN
7,100812,Athens State University,Athens,AL,35611,3.0,NaN,1,1,3,...,NaN,NaN,NaN,1,0.3459,0.6541,805.0,NaN,171.0,NaN
8,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,3.0,NaN,1,1,3,...,520.0,NaN,NaN,1,0.3806,0.6194,1331.0,2.0,NaN,902.0
9,100858,Auburn University,Auburn,AL,36849,3.0,NaN,1,1,3,...,4179.0,NaN,NaN,1,0.5101,0.4899,3269.0,2.0,10.0,5023.0
10,100937,Birmingham Southern College,Birmingham,AL,35254,3.0,NaN,1,1,3,...,316.0,NaN,NaN,1,0.5103,0.4897,221.0,2.0,NaN,NaN
11,101028,Chattahoochee Valley Community College,Phenix City,AL,36869,2.0,NaN,1,1,2,...,NaN,0.022989,261.0,2,0.3539,0.6461,314.0,1.0,140.0,NaN
12,101073,Concordia College Alabama,Selma,AL,36701,3.0,NaN,1,1,3,...,233.0,NaN,NaN,1,0.5688,0.4312,127.0,1.0,NaN,NaN
13,101116,South University-Montgomery,Montgomery,AL,36116,3.0,NaN,0,11,2,...,46.0,NaN,NaN,1,0.2866,0.7134,12187.0,2.0,NaN,74.0
14,101143,Enterprise State Community College,Enterprise,AL,36330-1300,2.0,NaN,1,1,2,...,NaN,0.240781,461.0,2,0.6077,0.3923,335.0,1.0,304.0,NaN
15,101161,Coastal Alabama Community College,Bay Minette,AL,36507-2698,2.0,NaN,1,1,2,...,NaN,0.353687,868.0,2,0.3661,0.6339,824.0,1.0,157.0,NaN
16,101189,Faulkner University,Montgomery,AL,36109-3390,3.0,NaN,1,1,3,...,171.0,NaN,NaN,1,0.3611,0.6389,1298.0,2.0,316.0,569.0
17,101240,Gadsden State Community College,Gadsden,AL,35903,2.0,NaN,1,1,2,...,NaN,0.211936,1307.0,2,0.3758,0.6242,5.0,1.0,272.0,NaN
18,101277,New Beginning College of Cosmetology,Albertville,AL,35951,NaN,NaN,1,1,1,...,NaN,0.083333,24.0,3,0.0000,1.0000,NaN,1.0,NaN,NaN
19,101286,George C Wallace Community College-Dothan,Dothan,AL,36303-9234,2.0,NaN,1,1,2,...,NaN,0.278402,801.0,2,0.3320,0.6680,0.0,1.0,253.0,NaN
20,101295,George C Wallace State Community College-Hance...,Hanceville,AL,35077-2000,2.0,NaN,1,1,2,...,NaN,0.300195,1026.0,2,0.3578,0.6422,1291.0,1.0,438.0,NaN
21,101301,George C Wallace State Community College-Selma,Selma,AL,36703-2808,2.0,NaN,1,1,2,...,NaN,0.175127,394.0,2,0.3197,0.6803,0.0,1.0,229.0,NaN
22,101365,Herzing University-Birmingham,Birmingham,AL,35209,2.0,NaN,0,11,2,...,44.0,NaN,NaN,1,0.3333,0.6667,3513.0,2.0,NaN,NaN
23,101435,Huntingdon College,Montgomery,AL,36106-2148,3.0,NaN,1,1,3,...,185.0,NaN,NaN,1,0.4946,0.5054,256.0,2.0,13.0,NaN
24,101453,Heritage Christian University,Florence,AL,35630-9977,3.0,NaN,1,1,3,...,4.0,NaN,NaN,1,0.8644,0.1356,21.0,1.0,1.0,26.0
25,101462,J. F. Drake State Community and Technical College,Huntsville,AL,35811,1.0,NaN,1,1,1,...,NaN,0.244444,180.0,2,0.3809,0.6191,0.0,1.0,136.0,NaN
26,101480,Jacksonville State University,Jacksonville,AL,36265,3.0,NaN,1,1,3,...,1120.0,NaN,NaN,1,0.4155,0.5845,2473.0,2.0,389.0,1291.0
27,101499,Jefferson Davis Community College,Brewton,AL,36426,2.0,NaN,1,1,2,...,NaN,0.196078,306.0,2,0.4504,0.5496,0.0,1.0,61.0,NaN
28,101505,Jefferson State Community College,Birmingham,AL,35215-3098,2.0,NaN,1,1,2,...,NaN,0.301676,1074.0,2,0.3983,0.6017,933.0,1.0,1016.0,NaN
29,101514,John C Calhoun State Community College,Tanner,AL,35671,2.0,NaN,1,1,2,...,NaN,0.332510,1215.0,2,0.4182,0.5818,1393.0,1.0,947.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7645,45316306,Strayer University-South Raleigh Campus,Raleigh,NC,27603,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7646,45321501,Strayer University-Willingboro Campus,Willingboro,NJ,08046,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7647,45321502,Strayer University-Lawrenceville,Lawrenceville,NJ,08648,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7648,45321503,Strayer University-Piscataway,Piscataway,NJ,08854,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7649,45484701,National Beauty College,Denver,CO,802231991,1.0,NaN,0,2,0,...,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
7650,45486501,Cambridge College of Healthcare & Technology,Atlanta,GA,303421731,2.0,NaN,0,2,0,...,NaN,NaN,NaN,2,NaN,NaN,19.0,NaN,NaN,NaN
7651,45538101,Utah County Campus,Orem,UT,840580000,1.0,NaN,0,2,0,...,NaN,NaN,NaN,3,NaN,NaN,36.0,NaN,NaN,NaN
7652,45666701,Strayer University-Columbus Campus,Columbus,OH,43240,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7653,45666702,Strayer University-Fairview Park Campus,Fairview Park,OH,44126,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7654,45666703,Strayer University-Akron Campus,Akron,OH,44320,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7655,45712901,Chamberlain College of Nursing-Miramar Campus,Miramar,FL,33027,3.0,NaN,0,8,0,...,NaN,NaN,NaN,1,NaN,NaN,1986.0,NaN,NaN,NaN
7656,45891901,Strayer University-Cobb Campus,Atlanta,GA,30339,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7657,45891902,Strayer University-Morrow Campus,Morrow,GA,30260,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7658,45891903,Strayer University-Roswell Campus,Roswell,GA,30076,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7659,45891904,Strayer University-Douglasville Campus,Douglasville,GA,30135,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7660,45891905,Strayer University-Lithonia Campus,Lithonia,GA,30038,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7661,45891906,Strayer University-Savannah Campus,Savannah,GA,31419,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7662,45891907,Strayer University-Augusta Campus,Augusta,GA,30909,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7663,45891908,Strayer University-Columbus,Columbus,GA,31909,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7664,45896401,Strayer University-Columbia Campus,Columbia,SC,29210,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7665,45896402,Strayer University-Charleston Campus,North Charleston,SC,29418,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7666,45897301,Strayer University-Irving,Irving,TX,75063,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7667,45897302,Strayer University-Katy,Houston,TX,77079,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7668,45897303,Strayer University-Northwest Houston,Houston,TX,77064,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7669,45897304,Strayer University-Plano,Plano,TX,75093,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7670,45920401,Unitek College,Fremont,CA,945383185,1.0,NaN,0,2,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
7671,46163401,Twin Rivers Adult School - Grand Avenue Center,Sacramento,CA,95838-3654,1.0,NaN,0,5,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
7672,46163402,Twin Rivers Adult School - Arnold Avenue Center,McClellan,CA,956521025,1.0,NaN,0,5,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
7673,46163403,Greater Sacramento Urban League,Sacramento,CA,958383738,1.0,NaN,0,5,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
7674,46163404,I-TAP,Sacramento,CA,95841-2989,1.0,NaN,0,5,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
for x in c_list:
    data5_2[x].replace(np.nan,0)

In [38]:
data5_2

,UNITID,INSTNM,CITY,STABBR,ZIP,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,...,DTRANS_4,TRANS_L4,DTRANS_L4,ICLEVEL,UGDS_MEN,UGDS_WOMEN,CDR2_DENOM,OPENADMP,UGNONDS,GRADS
0,100654,Alabama A & M University,Normal,AL,35762,3.0,NaN,1,1,3,...,1088.0,NaN,NaN,1,0.4786,0.5214,1438.0,2.0,16.0,794.0
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,3.0,NaN,1,1,3,...,1515.0,NaN,NaN,1,0.4154,0.5846,3160.0,2.0,274.0,6447.0
2,100690,Amridge University,Montgomery,AL,36117-3553,3.0,NaN,1,1,3,...,4.0,NaN,NaN,1,0.4389,0.5611,266.0,1.0,NaN,415.0
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,3.0,NaN,1,1,3,...,626.0,NaN,NaN,1,0.5402,0.4598,1208.0,2.0,180.0,1694.0
4,100724,Alabama State University,Montgomery,AL,36104-0271,3.0,NaN,1,1,3,...,1198.0,NaN,NaN,1,0.4054,0.5946,1957.0,2.0,24.0,682.0
5,100751,The University of Alabama,Tuscaloosa,AL,35487-0166,3.0,NaN,1,1,3,...,3642.0,NaN,NaN,1,0.4677,0.5323,3931.0,2.0,621.0,5413.0
6,100760,Central Alabama Community College,Alexander City,AL,35010,2.0,NaN,1,1,2,...,NaN,0.408072,446.0,2,0.3435,0.6565,430.0,1.0,113.0,NaN
7,100812,Athens State University,Athens,AL,35611,3.0,NaN,1,1,3,...,NaN,NaN,NaN,1,0.3459,0.6541,805.0,NaN,171.0,NaN
8,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,3.0,NaN,1,1,3,...,520.0,NaN,NaN,1,0.3806,0.6194,1331.0,2.0,NaN,902.0
9,100858,Auburn University,Auburn,AL,36849,3.0,NaN,1,1,3,...,4179.0,NaN,NaN,1,0.5101,0.4899,3269.0,2.0,10.0,5023.0
10,100937,Birmingham Southern College,Birmingham,AL,35254,3.0,NaN,1,1,3,...,316.0,NaN,NaN,1,0.5103,0.4897,221.0,2.0,NaN,NaN
11,101028,Chattahoochee Valley Community College,Phenix City,AL,36869,2.0,NaN,1,1,2,...,NaN,0.022989,261.0,2,0.3539,0.6461,314.0,1.0,140.0,NaN
12,101073,Concordia College Alabama,Selma,AL,36701,3.0,NaN,1,1,3,...,233.0,NaN,NaN,1,0.5688,0.4312,127.0,1.0,NaN,NaN
13,101116,South University-Montgomery,Montgomery,AL,36116,3.0,NaN,0,11,2,...,46.0,NaN,NaN,1,0.2866,0.7134,12187.0,2.0,NaN,74.0
14,101143,Enterprise State Community College,Enterprise,AL,36330-1300,2.0,NaN,1,1,2,...,NaN,0.240781,461.0,2,0.6077,0.3923,335.0,1.0,304.0,NaN
15,101161,Coastal Alabama Community College,Bay Minette,AL,36507-2698,2.0,NaN,1,1,2,...,NaN,0.353687,868.0,2,0.3661,0.6339,824.0,1.0,157.0,NaN
16,101189,Faulkner University,Montgomery,AL,36109-3390,3.0,NaN,1,1,3,...,171.0,NaN,NaN,1,0.3611,0.6389,1298.0,2.0,316.0,569.0
17,101240,Gadsden State Community College,Gadsden,AL,35903,2.0,NaN,1,1,2,...,NaN,0.211936,1307.0,2,0.3758,0.6242,5.0,1.0,272.0,NaN
18,101277,New Beginning College of Cosmetology,Albertville,AL,35951,NaN,NaN,1,1,1,...,NaN,0.083333,24.0,3,0.0000,1.0000,NaN,1.0,NaN,NaN
19,101286,George C Wallace Community College-Dothan,Dothan,AL,36303-9234,2.0,NaN,1,1,2,...,NaN,0.278402,801.0,2,0.3320,0.6680,0.0,1.0,253.0,NaN
20,101295,George C Wallace State Community College-Hance...,Hanceville,AL,35077-2000,2.0,NaN,1,1,2,...,NaN,0.300195,1026.0,2,0.3578,0.6422,1291.0,1.0,438.0,NaN
21,101301,George C Wallace State Community College-Selma,Selma,AL,36703-2808,2.0,NaN,1,1,2,...,NaN,0.175127,394.0,2,0.3197,0.6803,0.0,1.0,229.0,NaN
22,101365,Herzing University-Birmingham,Birmingham,AL,35209,2.0,NaN,0,11,2,...,44.0,NaN,NaN,1,0.3333,0.6667,3513.0,2.0,NaN,NaN
23,101435,Huntingdon College,Montgomery,AL,36106-2148,3.0,NaN,1,1,3,...,185.0,NaN,NaN,1,0.4946,0.5054,256.0,2.0,13.0,NaN
24,101453,Heritage Christian University,Florence,AL,35630-9977,3.0,NaN,1,1,3,...,4.0,NaN,NaN,1,0.8644,0.1356,21.0,1.0,1.0,26.0
25,101462,J. F. Drake State Community and Technical College,Huntsville,AL,35811,1.0,NaN,1,1,1,...,NaN,0.244444,180.0,2,0.3809,0.6191,0.0,1.0,136.0,NaN
26,101480,Jacksonville State University,Jacksonville,AL,36265,3.0,NaN,1,1,3,...,1120.0,NaN,NaN,1,0.4155,0.5845,2473.0,2.0,389.0,1291.0
27,101499,Jefferson Davis Community College,Brewton,AL,36426,2.0,NaN,1,1,2,...,NaN,0.196078,306.0,2,0.4504,0.5496,0.0,1.0,61.0,NaN
28,101505,Jefferson State Community College,Birmingham,AL,35215-3098,2.0,NaN,1,1,2,...,NaN,0.301676,1074.0,2,0.3983,0.6017,933.0,1.0,1016.0,NaN
29,101514,John C Calhoun State Community College,Tanner,AL,35671,2.0,NaN,1,1,2,...,NaN,0.332510,1215.0,2,0.4182,0.5818,1393.0,1.0,947.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7645,45316306,Strayer University-South Raleigh Campus,Raleigh,NC,27603,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7646,45321501,Strayer University-Willingboro Campus,Willingboro,NJ,08046,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7647,45321502,Strayer University-Lawrenceville,Lawrenceville,NJ,08648,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7648,45321503,Strayer University-Piscataway,Piscataway,NJ,08854,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7649,45484701,National Beauty College,Denver,CO,802231991,1.0,NaN,0,2,0,...,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
7650,45486501,Cambridge College of Healthcare & Technology,Atlanta,GA,303421731,2.0,NaN,0,2,0,...,NaN,NaN,NaN,2,NaN,NaN,19.0,NaN,NaN,NaN
7651,45538101,Utah County Campus,Orem,UT,840580000,1.0,NaN,0,2,0,...,NaN,NaN,NaN,3,NaN,NaN,36.0,NaN,NaN,NaN
7652,45666701,Strayer University-Columbus Campus,Columbus,OH,43240,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7653,45666702,Strayer University-Fairview Park Campus,Fairview Park,OH,44126,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7654,45666703,Strayer University-Akron Campus,Akron,OH,44320,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7655,45712901,Chamberlain College of Nursing-Miramar Campus,Miramar,FL,33027,3.0,NaN,0,8,0,...,NaN,NaN,NaN,1,NaN,NaN,1986.0,NaN,NaN,NaN
7656,45891901,Strayer University-Cobb Campus,Atlanta,GA,30339,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7657,45891902,Strayer University-Morrow Campus,Morrow,GA,30260,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7658,45891903,Strayer University-Roswell Campus,Roswell,GA,30076,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7659,45891904,Strayer University-Douglasville Campus,Douglasville,GA,30135,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7660,45891905,Strayer University-Lithonia Campus,Lithonia,GA,30038,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7661,45891906,Strayer University-Savannah Campus,Savannah,GA,31419,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7662,45891907,Strayer University-Augusta Campus,Augusta,GA,30909,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7663,45891908,Strayer University-Columbus,Columbus,GA,31909,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7664,45896401,Strayer University-Columbia Campus,Columbia,SC,29210,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7665,45896402,Strayer University-Charleston Campus,North Charleston,SC,29418,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7666,45897301,Strayer University-Irving,Irving,TX,75063,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7667,45897302,Strayer University-Katy,Houston,TX,77079,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7668,45897303,Strayer University-Northwest Houston,Houston,TX,77064,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7669,45897304,Strayer University-Plano,Plano,TX,75093,3.0,NaN,0,84,0,...,NaN,NaN,NaN,1,NaN,NaN,22208.0,NaN,NaN,NaN
7670,45920401,Unitek College,Fremont,CA,945383185,1.0,NaN,0,2,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
7671,46163401,Twin Rivers Adult School - Grand Avenue Center,Sacramento,CA,95838-3654,1.0,NaN,0,5,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
7672,46163402,Twin Rivers Adult School - Arnold Avenue Center,McClellan,CA,956521025,1.0,NaN,0,5,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
7673,46163403,Greater Sacramento Urban League,Sacramento,CA,958383738,1.0,NaN,0,5,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
7674,46163404,I-TAP,Sacramento,CA,95841-2989,1.0,NaN,0,5,0,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN